apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: entmoot-production
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: patch-statefulset.yaml
  - path: patch-pdb.yaml
  - path: patch-service-client.yaml
