apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - service-headless.yaml
  - service-client.yaml
  - statefulset.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml
images:
  - name: entmoot
    newTag: latest
